config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

resources :blog_posts

  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  # get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  # patch "/blog_posts/:id", to: "blog_posts#update"
  # delete "/blog_posts/:id", to: "blog_posts#destroy"
  # get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  # post "/blog_posts", to: "blog_posts#create", as: :blog_posts
  # get "/blog_posts", to: "blog_posts#index", as: :blog_posts

  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :blog_posts

end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
    belongs_to :author

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :set_blog_post, except: [:index, :new, :create]
  #only: [:show, :edit, :update, :destroy]

    def index
      @blog_posts = BlogPost.order(created_at: :desc).all
    end
  
    def show
    end
  
    def new
      @blog_post = BlogPost.new
    end
  
    def create
      @blog_post = BlogPost.new(blog_post_params)
      if Author.second.present?
        @blog_post.author = Author.second
      else
        @blog_post.author = Author.create(name: 'jojo bakalman')
      end
      if @blog_post.save
        redirect_to @blog_post
      else
        render :new, status: :unprocessable_entity
      end
    end
    
  
    def edit
    end
  
    def update
      if @blog_post.update(blog_post_params)
        redirect_to @blog_post
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @blog_post.destroy
      redirect_to root_path
    end
      
  
    private
  
    def blog_post_params
      params.require(:blog_post).permit(:title, :body)
    end
  
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_editbutton.html.erb
<%= link_to "Edit", edit_blog_post_path(@blog_post), class: "inline-block text-white bg-gradient-to-r from-blue-500 
    via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 
    focus:outline-none focus:ring-blue-300
    font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 my-2 mt-2" %>

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post, html: { class: "bg-white p-6 rounded drop-shadow-lg rounded-xl" } do |form| %>
    <% if form.object.errors.any? %>
        <div class="mb-4">
            <% form.object.errors.full_messages.each do |message| %>
                <div class="bg-red-100 border border-red-400 text-red-700 
                px-4 py-3 rounded relative" role="alert"><%= message %></div>
            <% end %>
        </div>
    <% end %>
 
    <div class="mb-4">
        <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_field :title, class: "shadow appearance-none border rounded 
        w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none 
        focus:shadow-outline" %>
    </div>
 

    <div class="mb-4">
        <%= tinymce %>
        <%= form.label :body, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_area :body, class: "cursor-text tinymce shadow appearance-none border 
        rounded w-full py-2 px-3 text-gray-700 leading-tight 
        focus:outline-none focus:shadow-outline" %>
    </div>

    <%= form.submit "Submit", class: "text-white bg-gradient-to-r from-blue-500 
    via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 
    focus:outline-none focus:ring-blue-300
    font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 cursor-pointer" %>

<% end %>

app/views/blog_posts/_homebutton.html.erb
<%= link_to "Home", root_path, class: "inline-block text-white bg-gradient-to-r 
from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br 
focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg
 text-sm px-5 py-2.5 text-center mr-2 mb-2 mt-2" %>

app/views/blog_posts/edit.html.erb
<h1 class="text-3xl font-bold text-black mb-2">Edit Blog Post</h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>

<div class="flex justify-center items-center mt-5">
<%= button_to "Delete", blog_post_path(@blog_post), method: :delete,
 data: {turbo_confirm: "Are you sure?"}, class: "text-white bg-gradient-to-r 
 from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 
 focus:outline-none focus:ring-red-300
  font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-5 mb-2" %>
<%= render 'homebutton' %>
</div>

app/views/blog_posts/index.html.erb
<div class="flex items-end">
  <img src="<%= image_path 'blogs.svg' %>" class="mr-4">
  <%= link_to "New post", new_blog_post_path, class: "inline-block text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-md px-5 py-2.5 text-center mr-2 mb-2" %>
</div>

<% @blog_posts.each do |blog_post| %>
  <div class="my-4 p-10 bg-white drop-shadow-xl rounded-xl flex flex-col">
    <h2 class="text-3xl font-bold text-black mb-2">
      <%= link_to blog_post.title, blog_post, class: "text-rails-red underline hover:text-black" %>
    </h2>
    <p class="text-gray-700 text-lg blog-post-body">
      <%= truncate(blog_post.body.html_safe, length: 200, escape: false) %>
    </p>
    <p class="mt-auto italic self-end">
      <%= blog_post.author.name %>
    </p>
  </div>
<% end %>

app/views/blog_posts/new.html.erb
<h1 class="pt-5 text-5xl font-bold mb-6 flex justify-center items-center">New Blog Post</h1>


<%= render partial: "form", locals: {blog_post: @blog_post} %>
<%= render 'homebutton' , class: "mt-5"%>

app/views/blog_posts/show.html.erb
<h1 class="pt-5 text-5xl font-bold text-rails-red mb-6 justify-center items-center">
  <%= @blog_post.title %>
</h1>
<div class="w-full text-right">
  <p class="pb-5 italic">
    <%= @blog_post.author.name %>
  </p>
</div>
<div class="text-xl text-gray-700 blog-post-body">
  <%= @blog_post.body.html_safe %>
</div>
<%= render 'editbutton' %>
<%= render 'homebutton' %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wow Blogs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= tinymce_assets %>
<script type="text/javascript" src="/assets/tinymce.js"></script>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="flex justify-center items-center min-h-screen no-underline bg-dirty-white">

    <div class="w-full max-w-2xl">
      <%= yield %>
    </div>


  </body>
</html>